### PR TITLE
Allow the req.user[role] to be an array of roles

### PR DESCRIPTION
**Pull request by czytelny**
Hi, nice lib - perfectly fit my needs:) would you mind to merge this pull request to master? perhaps it solves issue #3

### CODE REVIEW

**Comment by BenoitRanque** [comment]
Hello @czytelny 

Seeing as @tenodi seems inactive, could you publish this fork on npm under a different name? I want to use it for a project I am working on, but cannot include it in my package.json without it being published.

P.S. Hurray for my first comment on GitHub!

P.P.S. I could publish it myself but it is *your* work. Still not sure how the etiquette works when it comes to these matters

**Comment by czytelny** [comment]
Hi @BenoitRanque in that case you can use direct link to my fork in your `package.json`:

```
"dependencies": {
    "permission": "git://github.com/czytelny/permission.git"
}
```
my change is also rather tiny, so i don't want to make separate npm entry only for that :)

**Comment by BenoitRanque** [comment]
@czytelny  Thank you!
Exactly the information I needed

Thanks again

Edit: install with npm: 
~~`npm install --save git://github.com/czytelny/permission.git`~~

`
npm install --save czytelny/permission
`

Generate package.json: 

`
"dependencies": {
    "permission": "github:czytelny/permission"
} 
`

**Comment by tenodi** [comment]
Hi, @czytelny. As I'm short on time, I invited you as a collaborator to this project.

**Comment by BenoitRanque** [comment]
My fork gets rid of the `passport.js` dependency, if anyone is interested.

**Comment by tenodi** [comment]
@BenoitRanque I gave you collaborator access as well. So, if this is something that you think is needed, feel free to contribute directly and assign someone to PR.

**Comment by BenoitRanque** [comment]
Thank you. My fork differs in that I got rid of the passport dependency. So
will keep separate.

**Comment by czytelny** [comment]
thanks! I was on holiday ;) i'll take a look on the weekend and try to push things further.

**Pull request closed without merging**
